-- Enable pgvector support in the database cluster
CREATE EXTENSION IF NOT EXISTS vector;

-- Tenant Developer Accounts
CREATE TABLE developer_accounts (
    developer_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    paddle_customer_id VARCHAR(255) UNIQUE,
    api_key_hash VARCHAR(64) UNIQUE NOT NULL,
    plan_tier VARCHAR(50) DEFAULT 'free',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Agent Session Context (Multi-Tenant Scoped)
CREATE TABLE agent_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    developer_id UUID REFERENCES developer_accounts(developer_id) ON DELETE CASCADE,
    agent_external_id VARCHAR(255) NOT NULL,
    session_metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(developer_id, agent_external_id)
);

-- Transactional Memory: Structured operational variables (ACID compliant)
CREATE TABLE agent_transactional_state (
    session_id UUID REFERENCES agent_sessions(session_id) ON DELETE CASCADE,
    state_key VARCHAR(255) NOT NULL,
    state_value JSONB NOT NULL,
    version_id INT DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (session_id, state_key)
);

-- Semantic Memory: High-dimensional search context (pgvector + full-text hybrid)
CREATE TABLE agent_semantic_memory (
    memory_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES agent_sessions(session_id) ON DELETE CASCADE,
    raw_content TEXT NOT NULL,
    embedding VECTOR(1024), -- Matched to 1024-dimensions generated by Amazon Titan Embeddings V2
    tsv TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', raw_content)) STORED,
    token_count INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- HNSW Cosine Proximity Index for fast, distributed semantic searches
CREATE INDEX IF NOT EXISTS semantic_memory_hnsw_idx 
ON agent_semantic_memory USING hnsw (embedding vector_cosine_ops);

-- Full-Text GIN Index for hybrid search keyword matching
CREATE INDEX IF NOT EXISTS agent_semantic_memory_tsv_idx 
ON agent_semantic_memory USING GIN (tsv);

-- Session lookup index for agent semantic memory filtering and cascades
CREATE INDEX IF NOT EXISTS agent_semantic_memory_session_idx 
ON agent_semantic_memory(session_id);

-- Ephemeral LangGraph Checkpoints with CockroachDB Row-Level TTL (14-day expiry)
CREATE TABLE IF NOT EXISTS agent_checkpoints (
    checkpoint_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES agent_sessions(session_id) ON DELETE CASCADE,
    checkpoint_ns VARCHAR(255) NOT NULL,
    thread_id VARCHAR(255) NOT NULL,
    checkpoint_data BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
) WITH (ttl_expire_after = '14 days');
